export const LOADING_REPOSITORIES = 'LOADING_REPOSITORIES'

export const LOADING = 'LOADING'

export const LOADING_SUCCESS = 'LOADING_SUCCESS'

export const LOADING_ERROR = 'LOADING_ERROR'

export const LOADING_NEXT_REPOSITORIES = 'LOADING_NEXT_REPOSITORIES'

export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES'

export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS'